server:
  port: 8900

spring:
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #default-zone: http://localhost:8761/eureka
      defaultZone: http://localhost:${server.port}/eureka
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 15

logging:
  level:
    com.netflix.eureka: off
    com.netflix.discovery: off
