logging:
  level:
    com.netflix.eureka: off
    com.netflix.discovery: off
spring:
  application:
    name: eureka-server
  profiles:
    active: dev
  config:
    import: "configserver:${CONFIG_SERVER_ADDR}"